# Generated by Django 3.2.25 on 2024-10-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0002_alter_blog_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='autor',
            field=models.CharField(max_length=100),
        ),
    ]
